import { geoAlbersUsa, geoPath } from 'd3-geo';
import { feature } from 'topojson-client';
import type { Feature, FeatureCollection, Geometry } from 'geojson';
import type { Topology } from 'topojson-specification';
import './style.css';
import { DATA_AS_OF,elections,events,profiles,seats,sources,states } from './data/data';
import type { Rating, State } from './data/model';
import { currentCaucusCounts,majorityText,simulatedCounts,type Assumptions } from './logic';

type Mode='holder'|'rating';
let mode:Mode='holder', competitive=false, selected:State|null=null, assumptions:Assumptions={};
let returnFocus:HTMLElement|null=null;
const stateByFips=new Map(states.map(s=>[s.fips,s]));
const seatById=new Map(seats.map(s=>[s.seatId,s]));
const profileByFips=new Map(profiles.map(p=>[p.stateFips,p]));
const electionByState=(s:State)=>elections.filter(e=>seatById.get(e.seatId)?.stateFips===s.fips);
const partyLabel={D:'民主党',R:'共和党',I:'無所属',vacant:'空席',unknown:'未確認'};
const ratingColors:Record<Rating,string>={'Solid D':'#174f9e','Likely D':'#4d80bd','Lean D':'#93b7dc','Toss Up':'#8a8178','Lean R':'#e59a9a','Likely R':'#cf5a5a','Solid R':'#a5262e',unavailable:'#d9d8d4'};

document.querySelector<HTMLDivElement>('#app')!.innerHTML=`
<header class="mast"><div class="eyebrow">2026 UNITED STATES SENATE</div><h1>上院の行方</h1><p class="dek">改選議席の現在地から、州の背景、多数派への道まで。予測ではなく、確認済みデータと未確認項目を分けて示します。</p><div class="dateline"><span>データ基準日 ${DATA_AS_OF}</span><span>通常改選 33議席</span><span>全100議席</span></div></header>
<main><section class="summary" aria-labelledby="current-heading"><div><p class="kicker">現在の会派構成</p><h2 id="current-heading">100議席の内訳</h2></div><div id="current-counts" class="counts"></div></section>
<section class="workspace"><div class="map-column"><div class="controls" aria-label="地図表示設定"><div class="segmented"><button data-mode="holder" class="active">現保有党</button><button data-mode="rating">選挙情勢</button></div><label class="switch"><input id="competitive" type="checkbox"><span>激戦のみ強調</span></label></div>
<div class="search-wrap"><label for="state-search">州を検索・選択</label><select id="state-search"><option value="">50州から選ぶ</option>${states.map(s=>`<option value="${s.fips}">${s.nameJa} / ${s.nameEn} (${s.abbr})</option>`).join('')}</select></div>
<div class="map-head"><div><p class="kicker">INTERACTIVE MAP</p><h2 id="map-heading">2026年の改選州</h2></div><p id="mode-note">色は対象議席の現保有党。州全体の支持傾向や勝敗予測ではありません。</p></div><div id="map" class="map" aria-label="米国50州地図"></div><div id="legend" class="legend"></div><p class="map-note">州の面積は議席数を表しません。アラスカとハワイは投影上、位置・縮尺が調整されています。★は特別選挙（確認済みデータに該当なし）。</p></div>
<aside id="detail" class="detail" aria-live="polite"><div class="empty-detail"><span>STATE BRIEFING</span><h2>州を選択してください</h2><p>地図または検索から、改選の有無を問わず全50州の情報へ移動できます。</p></div></aside></section>
<section class="sim" aria-labelledby="sim-heading"><div class="sim-title"><div><p class="kicker">多数派への道</p><h2 id="sim-heading">議席シミュレーション</h2><p>各改選議席の勝者会派を仮に指定します。初期値は現保有会派がすべて維持する仮定です。</p></div><button id="reset">初期状態へ戻す</button></div><div class="warning">仮定の結果です。選挙予測・勝率ではありません。</div><div id="sim-result"></div><details><summary>全33改選議席の仮定を変更</summary><div id="seat-controls" class="seat-controls"></div></details></section>
<section class="method"><p class="kicker">READING THE DATA</p><h2>表示の読み方</h2><div class="method-grid"><article><b>保有党と情勢は別</b><p>初期表示は現保有党、情勢表示は評価機関の分類です。未取得を安全・接戦に置き換えません。</p></article><article><b>背景原稿の欠測を明示</b><p>州別原稿は確認状態を表示します。未確認の人口・産業情報から投票行動を推定しません。</p></article><article><b>シミュレーションは仮定</b><p>非改選議席と各議席の仮定を合算します。フィルター表示は集計を変えません。</p></article></div></section></main><footer>制作データは静的に同梱。閲覧時に外部サイトへ接続しません。</footer>`;

function holderFor(s:State){const es=electionByState(s);if(!es.length)return 'none';const parties=[...new Set(es.map(e=>seatById.get(e.seatId)!.party))];return parties.length===1?parties[0]:'mixed'}
function ratingFor(s:State):Rating|'none'|'mixed'{const es=electionByState(s);if(!es.length)return'none';const rr=[...new Set(es.map(e=>e.rating.category))];return rr.length===1?rr[0]:'mixed'}
function isCompetitive(s:State){return electionByState(s).some(e=>['Toss Up','Lean D','Lean R'].includes(e.rating.category))}
function fill(s:State){if(mode==='holder'){return ({D:'#2166ac',R:'#b52b35',I:'#7b5b97',vacant:'#f2c14e',unknown:'#b8b7b3',none:'#ececea',mixed:'#725f4c'} as Record<string,string>)[holderFor(s)]}const r=ratingFor(s);return r==='none'?'#ececea':r==='mixed'?'#725f4c':ratingColors[r]}
function renderCounts(){const c=currentCaucusCounts(seats);document.querySelector('#current-counts')!.innerHTML=`<div class="count dem"><strong>${c.Democratic}</strong><span>民主党会派</span></div><div class="bar" aria-hidden="true"><i style="width:${c.Democratic}%"></i><i style="width:${c.Republican}%"></i></div><div class="count rep"><strong>${c.Republican}</strong><span>共和党会派</span></div>${c.unconfirmed?`<div class="count"><strong>${c.unconfirmed}</strong><span>未確認</span></div>`:''}`}
let geoFeatures:Feature<Geometry>[]=[];
async function initMap(){const topology=await fetch(`${import.meta.env.BASE_URL}data/states-10m.json`).then(r=>r.json()) as Topology;const collection=feature(topology,topology.objects.states) as unknown as FeatureCollection;geoFeatures=collection.features.filter(f=>stateByFips.has(String(f.id).padStart(2,'0')));renderMap()}
function renderMap(){const host=document.querySelector('#map')!;host.innerHTML='';const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 975 610');svg.setAttribute('role','group');svg.setAttribute('aria-label','州境地図。州検索でも同じ情報を選べます');const path=geoPath(geoAlbersUsa().scale(1275).translate([487.5,305]));geoFeatures.forEach(f=>{const fips=String(f.id).padStart(2,'0'),s=stateByFips.get(fips)!;const p=document.createElementNS(svg.namespaceURI,'path');p.setAttribute('d',path(f)||'');p.setAttribute('fill',fill(s));p.setAttribute('class',`${selected?.fips===fips?'selected ':''}${competitive&&!isCompetitive(s)?'muted':''}`);p.setAttribute('tabindex','0');p.setAttribute('role','button');p.setAttribute('aria-label',`${s.nameJa}、${electionByState(s).length?'2026年選挙あり':'2026年選挙なし'}`);p.addEventListener('click',ev=>selectState(s,ev.currentTarget as HTMLElement));p.addEventListener('keydown',ev=>{const key=(ev as KeyboardEvent).key;if(key==='Enter'||key===' '){ev.preventDefault();selectState(s,ev.currentTarget as HTMLElement)}});const title=document.createElementNS(svg.namespaceURI,'title');title.textContent=`${s.nameJa} (${s.abbr})`;p.append(title);svg.append(p)});host.append(svg);renderLegend()}
function renderLegend(){const items=mode==='holder'?[['#2166ac','民主党保有'],['#b52b35','共和党保有'],['#7b5b97','無所属'],['#ececea','選挙なし'],['#b8b7b3','未確認']]:[['#174f9e','Solid D'],['#93b7dc','Lean D'],['#8a8178','Toss Up'],['#e59a9a','Lean R'],['#a5262e','Solid R'],['#d9d8d4','未取得'],['#ececea','選挙なし']];document.querySelector('#legend')!.innerHTML=items.map(([c,l])=>`<span><i style="background:${c}"></i>${l}</span>`).join('')}
function refs(ids:string[]){const unique=[...new Set(ids)],list=unique.map(id=>sources.find(s=>s.sourceId===id)).filter(Boolean);return list.length?`<ol>${list.map(s=>`<li><a href="${s!.url}" target="_blank" rel="noreferrer">${s!.title}</a> — ${s!.publisher}（取得 ${s!.retrievedAt}）</li>`).join('')}</ol>`:'<p>この項目に紐づく出典は未登録です。</p>'}
function selectState(s:State,trigger?:HTMLElement){selected=s;if(trigger)returnFocus=trigger;renderMap();const es=electionByState(s),p=profileByFips.get(s.fips)!,stateSeats=seats.filter(x=>x.stateFips===s.fips);const ids=[...p.politicalBase.sourceIds,...p.industryAndIssues.sourceIds,...p.historicalTrajectory.sourceIds,...p.electionMeaning.sourceIds,...es.flatMap(e=>e.sourceIds)];const timeline=events.filter(e=>p.eventIds.includes(e.eventId));document.querySelector('#detail')!.innerHTML=`<button class="close" aria-label="州詳細を閉じる">×</button><p class="kicker">STATE BRIEFING</p><h2>${s.nameJa}</h2><p class="en">${s.nameEn} · ${s.abbr}</p><div class="status ${p.contentStatus==='未作成'?'pending':''}">${p.contentStatus} · 基準日 ${p.asOf}</div><div class="race-summary">${es.length?`<strong>2026年 ${es.map(e=>`Class ${seatById.get(e.seatId)!.senateClass} 通常選挙`).join(' / ')}</strong><span>情勢評価：${es.map(e=>e.rating.category==='unavailable'?'未取得':e.rating.category).join(' / ')}</span>`:'<strong>2026年の対象選挙なし</strong>'}</div><section class="brief"><h3>州の要約</h3><p>${p.politicalBase.text}</p><p>${p.industryAndIssues.text}</p><p>${p.historicalTrajectory.text}</p><p>${p.electionMeaning.text}</p></section><details open><summary>これまでの主な変化</summary>${timeline.length?timeline.map(e=>`<article><time>${e.period}</time><b>${e.title}</b><p>${e.eventText}</p></article>`).join(''):'<p class="missing">確認済み年表は0件です。州固有の出来事と政治的変化の照合が未完了であるため、件数を埋めていません。</p>'}</details><details><summary>候補者・議席情報</summary>${stateSeats.map(x=>`<div class="seat"><b>${x.seatId} · Class ${x.senateClass}</b><span>現保有党：${partyLabel[x.party]} / 会派：${x.caucus==='Democratic'?'民主党':x.caucus==='Republican'?'共和党':'未確認'}</span><span>現職名：${x.incumbent??'基準日時点の確認未完了'}</span><span>次の通常改選：${x.senateClass===1?'2028年':x.senateClass===2?'2026年':'2030年'}</span></div>`).join('')}</details><details><summary>出典・情報時点</summary>${refs(ids)}</details>`;document.querySelector<HTMLButtonElement>('.close')!.onclick=()=>{selected=null;renderMap();document.querySelector('#detail')!.innerHTML='<div class="empty-detail"><span>STATE BRIEFING</span><h2>州を選択してください</h2><p>地図または検索から全50州の情報へ移動できます。</p></div>';returnFocus?.focus()};if(window.innerWidth<800)document.querySelector('#detail')!.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}
function renderSim(){const c=simulatedCounts(seats,elections,assumptions),changed=Object.entries(assumptions).filter(([id,v])=>seatById.get(id)?.caucus!==v);document.querySelector('#sim-result')!.innerHTML=`<div class="projected"><div><strong>${c.Democratic}</strong><span>民主党会派</span></div><div><strong>${c.Republican}</strong><span>共和党会派</span></div><div class="majority"><b>${majorityText(c)}</b><small>新議会（2027年1月3日以降）の仮定</small></div></div><p class="changes">変更：${changed.length?changed.map(([id,v])=>`${id} → ${v==='Democratic'?'民主党':'共和党'}会派`).join('、'):'なし'}</p>`;document.querySelector('#seat-controls')!.innerHTML=elections.map(e=>{const s=seatById.get(e.seatId)!,st=stateByFips.get(s.stateFips)!,v=assumptions[s.seatId]||s.caucus;return `<label><span>${st.nameJa}<small>${s.seatId} · 現${partyLabel[s.party]}</small></span><select data-seat="${s.seatId}"><option value="Democratic" ${v==='Democratic'?'selected':''}>民主党会派</option><option value="Republican" ${v==='Republican'?'selected':''}>共和党会派</option><option value="unconfirmed" ${v==='unconfirmed'?'selected':''}>未確定</option></select></label>`}).join('');document.querySelectorAll<HTMLSelectElement>('[data-seat]').forEach(el=>el.onchange=()=>{assumptions[el.dataset.seat!]=el.value as Assumptions[string];renderSim()})}
document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode as Mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));document.querySelector('#mode-note')!.textContent=mode==='holder'?'色は対象議席の現保有党。州全体の支持傾向や勝敗予測ではありません。':'色は統一評価機関の分類。現時点では評価未取得を明示しています。';renderMap()});
document.querySelector<HTMLInputElement>('#competitive')!.onchange=e=>{competitive=(e.target as HTMLInputElement).checked;renderMap()};document.querySelector<HTMLSelectElement>('#state-search')!.onchange=e=>{const s=stateByFips.get((e.target as HTMLSelectElement).value);if(s)selectState(s,e.target as HTMLElement)};document.querySelector<HTMLButtonElement>('#reset')!.onclick=()=>{assumptions={};renderSim()};
renderCounts();renderSim();initMap().catch(()=>{document.querySelector('#map')!.innerHTML='<p class="error">同梱された州境データを読み込めませんでした。ローカル開発サーバーまたはプレビューで開いてください。</p>'});
